import { Container } from "@chakra-ui/layout";
import Head from "next/head";
import Hero from "../components/Hero";

export default function Home() {
  return (
    <Container maxW="1200px">
      <Head>
        <title>Diego Camy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
    </Container>
  );
}
