import { Container } from "@chakra-ui/layout";
import Head from "next/head";
import React from "react";
import Hero from "../components/Hero";
import Projects from "../components/Projects";
import Technologies from "../components/Technologies";

export default function Home() {
  return (
    <Container maxW="1200px">
      <Head>
        <title>Diego Camy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Technologies />
      <Projects />
    </Container>
  );
}
